### ISSUE TITLE
No answer obtained

### ISSUE THREAD

**Issue by iitjee** [MusabShakeel576/quickfix.ai#1]
I've put an API key in hte popup.js file, but it still fails to retreive any results. Is this project discontinued?

**Comment by MusabShakeel576** [comment]
@iitjee you have to enter OpenAI API key in [backend env](https://github.com/MusabShakeel576/quickfix.ai/blob/df05c134a4cfabfc4274e3f0484a19cb41c3288a/backend/.env.example) and API URL in [chrome extension env](https://github.com/MusabShakeel576/quickfix.ai/blob/df05c134a4cfabfc4274e3f0484a19cb41c3288a/chrome-extension/env.js). There is no need to update the popup.js file.

**Comment by iitjee** [comment]
how do i run a python-based server?

**Comment by MusabShakeel576** [comment]
@iitjee To run python server specifically for Quickfix AI, you need to have Python v3.10 and Poetry installed. Then follow the steps:
1. Clone this Quickfix AI repository.
2. Build the server using `make install-backend` command
3. Update the environment variable in the `/backend/.env` file
4. Run the server using `make run-backend` command
